import { Activity, CreditCard, ShieldAlert, Trophy, Users } from "lucide-react";
import Link from "next/link";
import { getAdminStats } from "@/features/admin/actions";

export default async function AdminDashboard() {
  const result = await getAdminStats();
  if (!result.success || !result.data) return <main className="min-h-screen bg-black p-8 text-center text-red-300">{result.error ?? "Unable to load the command center."}</main>;
  const stats = result.data;
  return <main className="min-h-screen bg-black p-4 pb-24 text-slate-100"><header className="pt-2"><h1 className="text-3xl font-black tracking-tight text-white">Command center</h1><p className="mt-1 text-sm text-slate-400">VELOX platform operations.</p></header><section className="mt-6 grid grid-cols-2 gap-3"><Kpi icon={<Users className="h-5 w-5 text-blue-300" />} label="Total players" value={stats.totalUsers} /><Kpi icon={<Trophy className="h-5 w-5 text-amber-300" />} label="Active tournaments" value={stats.activeTournaments} /><Kpi icon={<Activity className="h-5 w-5 text-violet-300" />} label="Confirmed entries" value={stats.registrations} /><Kpi icon={<CreditCard className="h-5 w-5 text-cyan-300" />} label="Pending payments" value={stats.pendingPayments} /></section><section className="mt-5 rounded-2xl border border-red-500/20 bg-red-500/5 p-4"><div className="flex items-center justify-between gap-3"><div><p className="flex items-center gap-2 font-bold text-red-100"><ShieldAlert className="h-5 w-5" aria-hidden />Open disputes</p><p className="mt-1 text-sm text-red-200/70">{stats.pendingDisputes} awaiting moderator review</p></div><Link href="/admin/disputes" className="rounded-lg bg-red-500 px-3 py-2 text-sm font-bold text-white hover:bg-red-400">Review</Link></div></section><section className="mt-6 grid gap-3"><AdminLink href="/admin/tournaments" title="Tournament administration" description="Create events, manage games, brackets, and safe cancellations." /><AdminLink href="/admin/finance" title="Financial operations" description="Review verified payments and process supported Stars refunds." /><AdminLink href="/admin/disputes" title="Dispute review" description="Resolve match disputes with an immutable moderator trail." /></section><section className="mt-6"><h2 className="text-lg font-bold text-white">Recent financial activity</h2><div className="mt-3 overflow-hidden rounded-2xl border border-white/5 bg-slate-900">{stats.recentTransactions.length === 0 ? <p className="p-4 text-center text-sm text-slate-500">No transactions yet.</p> : stats.recentTransactions.map((transaction) => <div key={transaction.id} className="flex items-center justify-between border-b border-white/5 p-4 last:border-0"><div><p className="font-semibold text-white">{transaction.wallet.user.username ?? transaction.wallet.user.firstName ?? "VELOX player"}</p><p className="text-xs uppercase text-slate-500">{transaction.type.replaceAll("_", " ")} · {transaction.status}</p></div><span className="font-bold text-white">⭐ {transaction.amount}</span></div>)}</div></section></main>;
}

function Kpi({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) {
  return <div className="rounded-2xl border border-white/5 bg-slate-900 p-4"><span>{icon}</span><p className="mt-3 text-2xl font-black text-white">{value}</p><p className="mt-1 text-xs font-bold uppercase text-slate-500">{label}</p></div>;
}

function AdminLink({ href, title, description }: { href: string; title: string; description: string }) {
  return <Link href={href} className="rounded-2xl border border-white/5 bg-slate-900 p-4 transition hover:border-violet-400/40"><p className="font-bold text-white">{title}</p><p className="mt-1 text-sm leading-relaxed text-slate-400">{description}</p></Link>;
}
