import { ChevronLeft, ReceiptText } from "lucide-react";
import Link from "next/link";
import { getWalletTransaction } from "@/features/wallet/services";

export default async function TransactionDetailsPage({ params }: PageProps<"/wallet/transactions/[id]">) {
  const { id } = await params;
  const result = await getWalletTransaction(id);
  if (!result.success || !result.data) return <main className="flex min-h-screen flex-col items-center justify-center bg-black p-6 text-center"><ReceiptText className="mb-4 h-14 w-14 text-slate-700" aria-hidden /><h1 className="text-xl font-bold text-white">Transaction unavailable</h1><p className="mt-2 text-sm text-slate-400">{result.error ?? "We couldn't find this transaction."}</p><Link href="/wallet" className="mt-5 text-sm font-semibold text-[#c5f94d]">Back to wallet</Link></main>;
  const transaction = result.data;
  const positive = ["PRIZE_REWARD", "REFUND", "BONUS", "ADMIN_CREDIT"].includes(transaction.type);
  return <main className="min-h-screen bg-black p-4 pb-24 text-slate-100"><header className="flex items-center gap-3 pt-2"><Link href="/wallet" className="flex h-10 w-10 items-center justify-center rounded-full border border-white/10 bg-slate-900"><ChevronLeft className="h-5 w-5" aria-hidden /></Link><div><h1 className="text-xl font-bold text-white">Transaction details</h1><p className="text-xs text-slate-500">Immutable ledger record</p></div></header><section className="mt-7 rounded-2xl border border-white/5 bg-slate-900 p-5 text-center"><p className="text-sm font-bold uppercase text-slate-500">{transaction.type.replaceAll("_", " ")}</p><p className={`mt-2 text-4xl font-black ${positive ? "text-emerald-300" : "text-white"}`}>{positive ? "+" : "-"} ⭐ {transaction.amount}</p><span className="mt-3 inline-block rounded-full bg-black px-3 py-1 text-xs font-bold text-slate-300">{transaction.status}</span></section><section className="mt-5 divide-y divide-white/5 overflow-hidden rounded-2xl border border-white/5 bg-slate-900">{[["Tournament", transaction.tournament?.title ?? "Not applicable"], ["Currency", transaction.currency], ["Created", transaction.createdAt.toLocaleString()], ["Completed", transaction.completedAt?.toLocaleString() ?? "Pending"], ["Reference", transaction.telegramPaymentId ?? "Not applicable"], ["Transaction ID", transaction.id]].map(([label, value]) => <div key={label} className="flex items-start justify-between gap-4 p-4"><span className="text-sm text-slate-500">{label}</span><span className="break-all text-right text-sm font-medium text-slate-200">{value}</span></div>)}</section>{transaction.description && <p className="mt-4 rounded-xl border border-white/5 bg-slate-900 p-4 text-sm text-slate-400">{transaction.description}</p>}</main>;
}
