"use client";

import { useState, type FormEvent } from "react";
import { ChevronLeft, ShieldAlert } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { resolveDispute } from "@/features/matches/actions";

type Dispute = { id: string; reason: string; createdAt: Date; match: { id: string; tournament: { title: string }; player1Id: string | null; player2Id: string | null; team1Id: string | null; team2Id: string | null } };

export function DisputesClient({ disputes }: { disputes: Dispute[] }) {
  const router = useRouter();
  const [pending, setPending] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  async function resolve(event: FormEvent<HTMLFormElement>, dispute: Dispute) { event.preventDefault(); const form = new FormData(event.currentTarget); const winnerId = String(form.get("winnerId") || ""); setPending(dispute.id); const result = await resolveDispute({ disputeId: dispute.id, resolutionNotes: form.get("notes"), winnerId: winnerId || undefined, score1: winnerId ? Number(form.get("score1")) : undefined, score2: winnerId ? Number(form.get("score2")) : undefined }); setPending(null); setMessage(result.success ? "Dispute resolution recorded." : result.error ?? "Unable to resolve dispute."); if (result.success) router.refresh(); }
  return <main className="min-h-screen bg-black p-4 pb-24 text-slate-100"><header className="flex items-center gap-3 pt-2"><Link href="/admin" className="flex h-10 w-10 items-center justify-center rounded-full border border-white/10 bg-slate-900"><ChevronLeft className="h-5 w-5" aria-hidden /></Link><div><h1 className="text-2xl font-black text-white">Dispute review</h1><p className="text-sm text-slate-400">A moderator decision is stored with an audit trail.</p></div></header>{message && <p role="status" className="mt-4 rounded-xl border border-white/10 bg-slate-900 p-3 text-sm text-slate-200">{message}</p>}<section className="mt-6 space-y-4">{disputes.length === 0 ? <div className="rounded-2xl border border-white/5 bg-slate-900 p-8 text-center"><ShieldAlert className="mx-auto h-10 w-10 text-slate-700" aria-hidden /><p className="mt-3 text-sm text-slate-500">No open disputes.</p></div> : disputes.map((dispute) => { const participants = [dispute.match.player1Id ?? dispute.match.team1Id, dispute.match.player2Id ?? dispute.match.team2Id].filter((id): id is string => Boolean(id)); return <article key={dispute.id} className="rounded-2xl border border-red-500/15 bg-slate-900 p-4"><p className="text-xs font-bold uppercase text-violet-300">{dispute.match.tournament.title}</p><p className="mt-3 text-sm leading-relaxed text-slate-300">{dispute.reason}</p><p className="mt-2 text-xs text-slate-500">Opened {new Date(dispute.createdAt).toLocaleString()}</p><form onSubmit={(event) => resolve(event, dispute)} className="mt-4 grid gap-3"><label className="text-sm font-semibold text-slate-300">Resolution notes<textarea name="notes" required minLength={10} maxLength={1000} rows={3} className="mt-1 w-full rounded-xl border border-white/10 bg-black p-3 text-white" placeholder="Evidence reviewed and decision rationale" /></label><label className="text-sm font-semibold text-slate-300">Winner (optional to close without a decision)<select name="winnerId" className="mt-1 w-full rounded-xl border border-white/10 bg-black p-3 text-white"><option value="">Close without awarding a winner</option>{participants.map((id, index) => <option key={id} value={id}>Participant {index + 1}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><input name="score1" type="number" min="0" placeholder="Score 1" className="rounded-xl border border-white/10 bg-black p-3 text-white" /><input name="score2" type="number" min="0" placeholder="Score 2" className="rounded-xl border border-white/10 bg-black p-3 text-white" /></div><Button type="submit" disabled={pending === dispute.id} className="bg-violet-600 font-bold hover:bg-violet-500">{pending === dispute.id ? "Recording…" : "Record resolution"}</Button></form></article>; })}</section></main>;
}
